Sharma_Academy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('enrollment/', include('enrollment.urls')),
    path('course/', include('courses.urls')),
    path('assessment/', include('assessment.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

assessment/urls.py
from django.urls import path

from assessment.views import (AddAssessmentView, AddChoiceView,
                              AddQuestionView, QuestionDeleteView,
                              QuestionListView, QuestionUpdateView,
                              ShowAssessmentView, ShowQuizView, rating_quiz)

urlpatterns = [
    path('show-assessment/', ShowAssessmentView.as_view(), name='show-assessment'),
    path('add-assessment/', AddAssessmentView.as_view(), name='add-assessment'),
    path('add-question/', AddQuestionView.as_view(), name='add-question'),
    path('add-choice/', AddChoiceView.as_view(), name='add-choice'),
    # question crud
    path('show-question/', QuestionListView.as_view(), name='show-question'),
    path('delete-question/<int:pk>/',
         QuestionDeleteView.as_view(), name='delete-question'),
    path('update-question/<int:pk>/',
         QuestionUpdateView.as_view(), name='update-question'),
    # path('quiz/', QuizView.as_view(), name = 'quiz'),
    # path('text-quiz/', TextquizView.as_view(), name = 'text_quiz'),
    path('show-quiz/<str:pk>/', ShowQuizView.as_view(), name='show-quiz'),
    path('rating/', rating_quiz, name='rating'),
]

users/urls.py
from django.contrib.auth.views import (PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from users.views import (ActivateView, LoginView, RegisterView, index,
                         logout_view)

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('activate/<uidb64>/<token>',
         ActivateView.as_view(), name='activate'),
    path('index/', index, name='index'),
    path('logout/', logout_view, name='logout'),

    # forgot password urls

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html'),
        name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
]

assessment/models.py
from django.db import models

from courses.models import Course
from users.models import CustomUser

# Create your models here.


class Assessment(models.Model):

    TYPE = (
        ('mcq', 'MCQ'),
        ('short answer', 'Short Answer'),
        ('essay', 'Essay'),
    )

    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    # duration = models.CharField(max_length = 100)
    duration = models.DurationField()
    type = models.CharField(max_length=100,
                            choices=TYPE, default='mcq')

    def __str__(self):
        return self.title


class Question(models.Model):

    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE)
    question = models.CharField(max_length=255)

    def __str__(self):
        return self.question


class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    option = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.option


class Answer(models.Model):

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(blank=True)


class Rating(models.Model):

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE)
    rating = models.IntegerField()

    def __str__(self):
        return f'{self.user} rated {self.rating} star for {self.assessment}'

assessment/forms.py
from django import forms

from assessment.models import Answer, Assessment, Choice, Question, Rating


class AssessmentForm(forms.ModelForm):

    class Meta:
        model = Assessment
        fields = '__all__'
        # widgets = {
        #     'duration' : forms.TextInput(attrs={'class':'durationInputWidget'})
        # }


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = '__all__'


class ChoiceForm(forms.ModelForm):

    class Meta:
        model = Choice
        fields = '__all__'


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer
        # fields = ['content']
        fields = '__all__'
        widgets = {
            'question': forms.HiddenInput(),
            'user': forms.HiddenInput(),
            'rating': forms.HiddenInput(),
        }

    # def __init__(self, *args, **kwargs):
    #     user = kwargs.pop('user', None)
    #     super(AnswerForm, self).__init__(*args, **kwargs)
    #     if user:
    #         self.fields['user'].initial = user

    # def __init__(self, *args, **kwargs):
    #     super(AnswerForm, self).__init__(*args, **kwargs)
    #     self.fields['user'].queryset = CustomUser.objects.filter(type = 'instructor')


class RatingForm(forms.ModelForm):

    class Meta:
        model = Rating
        fields = '__all__'

        widgets = {
            'user': forms.HiddenInput(),
            'assessment': forms.HiddenInput(),
            'rating': forms.HiddenInput(),
        }

assessment/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Avg
from django.forms import modelformset_factory
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from assessment.forms import (AnswerForm, AssessmentForm, ChoiceForm,
                              QuestionForm, RatingForm)
from assessment.models import (Answer, Assessment, Choice, Course, Question,
                               Rating)
# from assessment.utils import send_email_with_marks
from assessment.tasks import send_email_with_marks


class ShowAssessmentView(View):

    " Showing all assessment present in project "

    template_name = 'assessment/assessment.html'

    def get(self, request, *args, **kwargs):
        if 'q' in request.GET:
            q = request.GET['q']
            assessment = Assessment.objects.filter(title__icontains=q)
        else:
            assessment = Assessment.objects.all()
        assessment = assessment.annotate(
            avg_rating=Avg('rating__rating', default=0))
        assessment_per_page = 5
        paginator = Paginator(assessment, assessment_per_page, orphans=2)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        return render(request, self.template_name, {'assessment': assessment,
                                                    'page_obj': page_obj})


class AddAssessmentView(View):

    " Define assessment type and course "

    form_class = AssessmentForm
    template_name = 'assessment/addassessment.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        user = request.user

        if user.type == 'instructor':
            if form.is_valid():
                form.save()
                return JsonResponse({'message': 'Assessment added successfully'})
            else:
                print(form.errors)
                return JsonResponse({'message': 'Assessment added failed'})
        else:
            return JsonResponse({'message': 'user is not instructor'})


class AddQuestionView(View):

    " Adding questions for assessment "

    form_class = QuestionForm
    template_name = "assessment/addQuestion.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        user = request.user

        if user.type == 'instructor':
            if form.is_valid():
                form.save()
                messages.error(request, 'Question added successfully.')
                return HttpResponseRedirect(reverse('add-question'))
            else:
                messages.error(request, 'Question add failed.')
                return HttpResponseRedirect(reverse('index'))
        else:
            messages.error(request, 'User is not instructor.')
            return HttpResponseRedirect(reverse('index'))


class AddChoiceView(View):

    " Adding questions for assessment "

    form_class = ChoiceForm
    template_name = "assessment/addChoice.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        user = request.user

        if user.type == 'instructor':
            if form.is_valid():
                form.save()
                messages.success(request, 'Choice added successfully.')
                return HttpResponseRedirect(reverse('add-choice'))
            else:
                messages.success(request, 'Choice add Failed.')
                return HttpResponseRedirect(reverse('index'))
        else:
            messages.error(request, 'User is not instructor.')
            return HttpResponseRedirect(reverse('index'))


class ShowQuizView(View):

    " Showing quiz according to user request "

    def get(self, request, *args, **kwargs):
        try:
            assessment = Assessment.objects.get(id=self.kwargs['pk'])
            if assessment.type == 'mcq':
                questions = assessment.question_set.all()
                return render(request, 'assessment/quiz.html', {'questions': questions,
                                                                'assessment': assessment, })
            else:
                questions = assessment.question_set.all()
                count = questions.count()
                user = request.user.id
                AnswerFormSet = modelformset_factory(
                    Answer, form=AnswerForm, extra=count)
                # AnswerFormSet.form = staticmethod(curry(AnswerForm, user=request.user.id))
                formset = AnswerFormSet(queryset=Answer.objects.none())
                return render(request, 'assessment/showquiz.html', {'questions': questions,
                                                                    'formset': formset,
                                                                    'user': user,
                                                                    'assessment': assessment, })
        except Exception as e:
            messages.success(
                request, e)
            return HttpResponseRedirect(reverse("show-assessment"))

    def post(self, request, *args, **kwargs):
        assessment = Assessment.objects.get(id=self.kwargs['pk'])
        if assessment.type == 'mcq':
            if assessment.id in request.session:
                messages.success(request, 'Assessment already submitted.')
                return HttpResponseRedirect(reverse("show-assessment"))
            score = 0
            for q in Question.objects.all():
                select_option_id = request.POST.get(f'q_{q.id}')
                if select_option_id:
                    select_option = Choice.objects.get(pk=select_option_id)
                    if select_option.correct:
                        score += 1
            request.session['assessment.id'] = True
            form = RatingForm
            # send_email_with_marks(request, score)
            email = request.user.email
            send_email_with_marks.apply_async(args=[email, score])
            messages.success(
                request, 'Answer submmited successfully. Check your email for score.')
            return render(request, 'assessment/score.html', {'score': score, 'form': form,
                                                             'assessment': assessment})
        else:
            questions = assessment.question_set.all()
            count = questions.count()
            AnswerFormSet = modelformset_factory(
                Answer, form=AnswerForm, extra=count)
            # AnswerFormSet.form = staticmethod(curry(AnswerForm, user=request.user.id))
            formset = AnswerFormSet(
                request.POST, queryset=Answer.objects.none())
            if formset.is_valid():
                if 'assessment_submitted' in request.session:
                    messages.success(request, 'Assessment already submitted.')
                    return HttpResponseRedirect(reverse("show-assessment"))
                request.session['assessment_submitted'] = True
                formset.save()
                form = RatingForm
                messages.success(request, 'Assessment submited successfully.')
                return render(request, 'assessment/score.html', {'form': form,
                                                                 'assessment': assessment})
            messages.success(request, 'Assessment submit failed.')
            return HttpResponseRedirect(reverse("show-assessment"))


def rating_quiz(request):
    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Rating submmited successfully.')
            return HttpResponseRedirect(reverse("show-assessment"))
        else:
            messages.error(request, 'Assessment Rating Failed.')
            return HttpResponseRedirect(reverse("show-assessment"))


class QuestionListView(ListView):
    model = Question
    template_name = "assessment/question.html"

class QuestionDeleteView(DeleteView):
    model = Question
    success_url = '/assessment/show-question/'
    template_name = "assessment/question_confirm_delete.html"


class QuestionUpdateView(UpdateView):
    model = Question
    fields = ['question']
    success_url = '/assessment/show-question/'
    template_name = "assessment/question_confirm_update.html"

assessment/templates/assessment/addChoice.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}Choice{% endblock title %}
{% block main %}

<div class="main-form container">
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="question">Question :- </label>
            <select class="form-control" id="question" name = "{{form.question.name}}">
              {% for q in form.question %}
              <option value="{{q.id}}">{{q}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <label for="option">Option :-</label>
            <input type="text" class="form-control" name="{{form.option.name}}" id="option"
              placeholder="create option"/>
          </div>
          <div class="form-check">
            <input type="checkbox" class="form-check-input" name="{{form.correct.name}}" id="correct">
            <label class="form-check-label" for="correct">Correct</label>
          </div>
        <input type="submit" value = "Add Choice" class="btn btn-primary">
    </form>

    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-info">
        {{ message }}
    </div>
    {% endfor %}

    {% endif %}
</div>

{% endblock main %}

assessment/templates/assessment/addQuestion.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}Question{% endblock title %}
{% block main %}

<div class="main-form container">
    <form action="{% url "add-question" %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="assessment">Assessment :- </label>
            <select class="form-control" id="assessment" name = "{{form.assessment.name}}">
              {% for a in form.assessment %}
              <option value="{{a.id}}">{{a}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <label for="question">Question :-</label>
            <input type="text" class="form-control" name="{{form.question.name}}" id="question"
              placeholder="create question"/>
          </div>
          <input type="submit" value = "Add Question" class="btn btn-primary">
    </form>
    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-info">
        {{ message }}
    </div>
    {% endfor %}

    {% endif %}
</div>

{% endblock main %}

assessment/templates/assessment/addassessment.html
{% extends "users/base.html" %} 
{% load static %}
{% comment %} {% load crispy_forms_tags %}{% endcomment %} 
{% block title %}Add assessment{% endblock title %} 
{% block main %}

<div class="main-form container">
  <h1>Add Assessment</h1>


  <div>
    <form action="#" method="post" id="assessment-form">
      {% csrf_token %} 
      <div class="form-group">
        <label for="course">Course :- </label>
        <select class="form-control" id="course" name = "{{form.course.name}}">
          {% for c in form.course %}
          <option value="{{c.id}}">{{c}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="title">Title :-</label>
        <input type="text" class="form-control" name="{{form.title.name}}" id="title"
          placeholder="Title"/>
      </div>
      <div class="form-group">
        <label for="duration">Duration :-</label>
        <input type="text" class="form-control" name="{{form.duration.name}}" id="duration"
          placeholder="Enter time in hh:mm:ss format."/>
      </div>
      <div class="form-group">
        <label for="type">Type :- </label>
        <select class="form-control" id="type" name="{{form.type.name}}">
          {% for t in form.type %}
          <option value="{{t.id}}">{{t}}</option>
          {% endfor %}
        </select>
      </div>
      {% comment %} {{form|crispy}} {% endcomment %}
      <button class="btn btn-primary add-assessment">Add</button>
    </form>
  </div>

  <div class="alert alert-info" id="msg" style="display: none"></div>

</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script src="{% static 'assessment/js/addassessment.js' %}"></script>
{% endblock main %}

assessment/templates/assessment/assessment.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}Assessment{% endblock title %}
{% block main %}


<div class="main-form container">

    <div class="py-4">
      <div class="row">
          <form class="form-inline my-2 my-lg-0" action="{% url "show-assessment" %}">
             <div class="col-4">
              <input class="form-control mr-sm-2 border border-primary" name="q" type="search" placeholder="Search" aria-label="Search">
             </div>
             <div class="col-8 my-4">
              <button class="btn btn-primary" type="submit">Search</button>
             </div>
          </form>
      </div>
    </div>

  <table class="table">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Type</th>
          <th scope="col">Duration</th>
          <th scope="col">Rating</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for a in page_obj %}
        <tr>
          <td>{{a.title}}</td>
          <td>{{a.type}}</td>
          <td>{{a.duration}}</td>
          <td>   
            <span class="fa fa-star {% if a.avg_rating > 0 %} four {% endif %}"></span>
            <span class="fa fa-star {% if a.avg_rating > 1 %} four {% endif %}"></span>
            <span class="fa fa-star {% if a.avg_rating > 2 %} four {% endif %}"></span>
            <span class="fa fa-star {% if a.avg_rating > 3 %} four {% endif %}" ></span>
            <span class="fa fa-star {% if a.avg_rating > 4 %} four {% endif %}"></span>
          </td>
          <td><a href="{% url "show-quiz" a.id %}" class="btn btn-primary">Start</a></td>
        </tr>
        {% endfor %}
      </tbody>
  </table>

  <div class="container p-4">
    <div class="pagination justify-content-center">
      <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1" class="btn btn-primary">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-primary">last &raquo;</a>
        {% endif %}
      </span>
    </div>
  </div>



  {% if messages %}

  {% for message in messages %}
  <div class="alert alert-info">
      {{ message }}
  </div>
  {% endfor %}

  {% endif %}
</div>

{% endblock main %}

assessment/templates/assessment/question.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}Question{% endblock title %}
{% block main %}

<div class="main container">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Question</th>
            <th scope="col">Delete</th>
            <th scope="col">Update</th>
          </tr>
        </thead>
        <tbody>
        {% for question in object_list %}
          <tr>
            <td>{{question}}</td>
            {% comment %} <td><a href="{% url "show-quiz" a.id %}">{{a.title}}</a></td> {% endcomment %}
            <td><span><a href="{% url "delete-question" question.id %}" class="btn btn-danger">Delete</a></span></td>
            <td><span><a href="{% url "update-question" question.id %}" class="btn btn-success">Update</a></span></td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
</div>
{% endblock main %}

assessment/templates/assessment/question_confirm_delete.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}Delete Confirm{% endblock title %}
{% block main %}

<div class="main-form container">
    <h1>confirm delete</h1>
    <p>Are you sure ?</p>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary"> confirm</button>
    </form>
    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-info">
        {{ message }}
    </div>
    {% endfor %}

    {% endif %}
</div>

{% endblock main %}

assessment/templates/assessment/question_confirm_update.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}Question update{% endblock title %}
{% block main %}

<div class="main-form container">
    <h1>Update here</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% comment %} {{form.as_p}} {% endcomment %}
        <label for="question">Question :-</label>
        <input type="text", name="question", value="{{question}}" class="form-control"> <br>
        <button type="submit" class="btn btn-primary auto">Update</button>
    </form>
    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-info">
        {{ message }}
    </div>
    {% endfor %}

    {% endif %}
</div>

{% endblock main %}

assessment/templates/assessment/quiz.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}Quiz{% endblock title %}
{% block main %}

<div class="main container">
    <form action="{% url "show-quiz" assessment.id %}" method="post" id = "test">
        {% csrf_token %}
        <div class="text-end"> Time left = <span id="timer">{{assessment.duration}}</span></div>
        {% if questions %}
            {% for q in questions %}
                <p>{{ q.question }}</p>
                {% for c in q.choice_set.all %}
                    <input type="radio" name = "q_{{ q.id }}" value="{{ c.id }}">{{ c.option }}<br>
                {% endfor %}
                <br>
            {% endfor %}
            <input type="submit" value="Submit" class="btn btn-primary">
        {% else %}
        <div class="main-form container">
            <h1 id="contain">No Questions Available if you are instructor please add questions first.</h1>
        {% endif %}
        </div>
    </form>

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}

</div>

<script>
startTimer();

function startTimer() {
  var presentTime = document.getElementById('timer').innerHTML;
  var timeArray = presentTime.split(/[:]+/);
  var h = timeArray[0];
  var m = timeArray[1];

  var s = checkSecond((timeArray[2] - 1));

  if(s == 59){
    m = m - 1
  }
  if(m == 0 & s == 0) {
    h = h-1;
    m = 60
  }
  if(h < 0){
    document.getElementById('test').submit()
    return
  }
  
  document.getElementById('timer').innerHTML =
   h + ":" + m + ":" + s;
  setTimeout(startTimer, 1000);

}

function checkSecond(sec) {
  if (sec < 10 && sec >= 0) {sec = "0" + sec}; // add zero in front of numbers < 10
  if (sec < 0) {sec = "59"};
  return sec;
}
</script>

{% endblock main %}

assessment/templates/assessment/score.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}Score{% endblock title %}
{% block main %}

<div class="main-form container">

    <h1>score:- {{ score }} </h1>

    <form action="{% url "rating" %}" method="post" id="rating-form">
        {% csrf_token %}

        {{form}}
        <div class="card"> 
            <h1>Rating for Quiz</h1> 
            <br/> 
            <div class="parent">
                <span onclick="gfg(1)" 
                class="star">★ 
                </span> 
                <span onclick="gfg(2)" 
                        class="star">★ 
                </span> 
                <span onclick="gfg(3)" 
                        class="star">★ 
                </span> 
                <span onclick="gfg(4)" 
                        class="star">★ 
                </span> 
                <span onclick="gfg(5)" 
                        class="star">★ 
                </span>
            </div> 
            <h3 id="output"> 
                Rating is: 0/5 
            </h3> 
        </div> 
        <input type="hidden" name="user" id="user" value="{{user.id}}">
        <input type="hidden" name="assessment" id="assessment" value="{{assessment.id}}">
        <input type="hidden" name="rating" id="rating" value="{{n}}">
    </form>

    <div class = "alert alert-info" id = "msg" style = "display : none">
    </div>

    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-info">
        {{ message }}
    </div>
    {% endfor %}
  
    {% endif %}
</div>

{% endblock main %}


{% comment %} 
                <input type="radio" name="{{rating}}" onclick="gfg(1)" 
                    class="star"  value="1"><span>★</span> 
                </input> 
                <input type="radio" name="{{rating}}" onclick="gfg(2)" 
                    class="star"  value="2"><span>★</span> 
                </input> 
                <input type="radio" name="{{rating}}" onclick="gfg(3)" 
                    class="star"  value="3"><span>★</span>  
                </input> 
                <input type="radio" name="{{rating}}" onclick="gfg(4)" 
                    class="star"  value="4"><span>★</span> 
                </input> 
                <input type="radio" name="{{rating}}" onclick="gfg(5)" 
                    class="star"  value="5"><span>★</span>
                </input>
 {% endcomment %}

assessment/templates/assessment/showquiz.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}Text Quiz{% endblock title %}
{% block main %}

<div class="main container">
    <form action="{% url "show-quiz" assessment.id %}" method="post" id="short_quiz">
        {% csrf_token %}
        {% if questions %}
            {{ formset.management_form }}
                {% for q in questions %}
                    <p class="fs-4">{{ q }}</p>
                    {% for form in formset %}
                        {% if forloop.counter == forloop.parentloop.counter %}
                            <input type='hidden' name="{{form.prefix}}-user" value="{{ user }}"/>
                            <input type='hidden' name="{{form.prefix}}-question" value="{{ q.id }}"/>
                            <div class="form-group">
                                <label for="content"></label>
                                  <textarea class="form-control" name="{{form.prefix}}-content" id="content" 
                                  placeholder="Enter Your Answer Here." rows="4" cols="50"></textarea>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                <input type="submit" value="Submit" class="btn btn-primary">
        {% else %}
        <div class="main-form container">
            <h1 id="contain">No Questions Available if you are instructor please add questions first.</h1>
        </div>
        {% endif %}
    </form>
</div>
{% endblock main %}